### PR TITLE
Arg add

### PR DESCRIPTION
**Pull request by telphan**

### CODE REVIEW

**Comment by dustybee** [comment]
Hello! I am sorry i have to do it this way. I could not find any other way to ask you a question.
I have a little problem... I created a .service file to start my program as a service and at boot. The program works fine when i start it with "sudo node app.js", but when i start it as a service, only my drawPixel() image shows up, not any of the drawText() text.

Do you have any idea why this is happening / how to fix this?

Another thing: I was stuck for a whole day trying to figure out how to draw text to the screen. Turns out i had to run the function like this: `drawText(X, Y, 'text', 'fontFile',  R,G,B)` instead of `drawText(X, Y, R, G, B, 'text', 'fontFile')` like the documentation says. Maybe i am doing something wrong and making it work in a way that that it is not supposed to.

**Comment by telphan** [comment]
Hi,
Not sure about the service problem you are facing, sounds to me like some sort of race condition, maybe drawText has a dependency that is not ready when your service is brought up. Apologies to be so vague, but I have not used `drawText()` in my projects.

This repo was forked from another that used an older version of the C++ library, we needed to updated to the latest version of the library, but have not updated the documentation too.

**Comment by dustybee** [comment]
Okay, i will look into it. thank you for the quick reply!

**Comment by dustybee** [comment]
After some more testing i found out that the current working directory had to be the directory app.js lives in.
running `sudo /etc/local/bin/node /home/pi/haltedisplay/app.js` from `/home/pi` didn't work, but it did work when i changed directory to `/home/pi/haltedisplay`. 

I fixed the service with `WorkingDirectory=/home/pi/haltedisplay`.
 Still weird that only `drawText()` didn't work.

**Pull request merged**
